# python_ai/rag/knowledge_base.py

DEFAULT_KNOWLEDGE_DOCUMENTS = [
    {
        "id": "doc_ftc_001",
        "title": "FTC Guidelines on Endorsements and Testimonials in Advertising",
        "category": "policy",
        "tags": ["ftc", "legal", "paid_reviews", "incentivized", "regulations"],
        "content": (
            "Federal Trade Commission (FTC) 16 CFR Part 255 dictates that material connections between "
            "an advertiser and an endorser must be fully and clearly disclosed. Paid reviews, incentivized feedback, "
            "and gift-for-rating arrangements without prominent disclosure constitute deceptive commercial practices. "
            "Reviews generated by seller employees, family members, or paid review brokers are strictly illegal. "
            "Key Indicators of FTC Non-Compliance: Lack of material connection disclosure ('Received free product for 5 stars'), "
            "suppression of negative reviews by sellers, and organized review exchange circles."
        )
    },
    {
        "id": "doc_amazon_002",
        "title": "Amazon Customer Review Creation & Anti-Spam Guidelines",
        "category": "policy",
        "tags": ["amazon", "e-commerce", "policy", "incentive", "bot_detection"],
        "content": (
            "Amazon Customer Review Policies explicitly prohibit any attempt to manipulate product ratings or reviews. "
            "Prohibited actions include: 1) Financial remuneration or discounts in exchange for 5-star ratings; "
            "2) Posting reviews on behalf of family, employees, or commercial entities; "
            "3) Rapid posting bursts where a newly listed product receives scores of identical 5-star reviews within hours; "
            "4) Competitor negative attacks (down-voting or fake 1-star reviews containing malicious text). "
            "Enforcement Actions: Suspicious reviews are purged, ASIN review privileges revoked, and seller accounts suspended."
        )
    },
    {
        "id": "doc_shopee_003",
        "title": "Shopee Review Integrity & Seller Conduct Standard",
        "category": "policy",
        "tags": ["shopee", "e-commerce", "policy", "southeast_asia", "review_farming"],
        "content": (
            "Shopee Anti-Fraud System flags artificial orders and review farming (also known as brush orders). "
            "Sellers using automated scripts, review exchange groups, or fake buyer profiles to artificially boost ratings "
            "face immediate shop restriction. Common Indicators on Shopee: Generic non-descriptive reviews ('Good product fast shipping thanks seller'), "
            "repeated identical photos uploaded across different user accounts, and review timestamps occurring in exact 5-second intervals."
        )
    },
    {
        "id": "doc_pattern_004",
        "title": "Fake Review Pattern #1: Sentiment-Rating Mismatch & Rating Manipulation",
        "category": "fraud_pattern",
        "tags": ["mismatch", "manipulated", "rating_bias", "sentiment", "heuristics"],
        "content": (
            "Rating-Sentiment Contradiction occurs when a reviewer assigns a 5-star rating while writing negative text "
            "('Arrived broken, terrible quality, waste of money'), or conversely a 1-star rating with praising text. "
            "This pattern typically indicates automated review injection scripts, seller rating hijacking, or compromised reviewer accounts. "
            "EchoTrace ML Classifier assigns high risk (Confidence >= 75%) to reviews exhibiting a sentiment polarity contradiction."
        )
    },
    {
        "id": "doc_pattern_005",
        "title": "Fake Review Pattern #2: Bot Networks & Copy-Paste Duplication",
        "category": "fraud_pattern",
        "tags": ["duplicate", "bot_farm", "text_similarity", "jaccard", "spam"],
        "content": (
            "Paid review farms deploy automated bots that reuse standardized template phrases across dozens of products. "
            "Detection Metrics: High Jaccard similarity (>= 75%) or TF-IDF cosine similarity between reviews posted across different accounts. "
            "Linguistic signatures: Excessive use of excited generic superlatives ('BEST PRODUCT EVER MUST BUY 10/10 WOW'), "
            "unusual capitalization, repetitive punctuation (!!!), and lack of specific product detail descriptions."
        )
    },
    {
        "id": "doc_pattern_006",
        "title": "Fake Review Pattern #3: Astroturfing & Burst Posting Anomalies",
        "category": "fraud_pattern",
        "tags": ["astroturfing", "burst", "timestamp_anomaly", "velocity", "manipulation"],
        "content": (
            "Astroturfing is the deceptive practice of creating a false impression of widespread grassroots support. "
            "In e-commerce, it manifests as sudden review velocity spikes (e.g., 50 positive reviews created in 2 hours for a product with previously low activity). "
            "Reviewers involved in astroturfing campaigns frequently display zero past review history, newly created accounts, "
            "and generic praise focused on brand name keywords."
        )
    },
    {
        "id": "doc_case_007",
        "title": "Historical Case Study #101: Syndicated Review Farm Network Attack",
        "category": "case_study",
        "tags": ["case_study", "review_farm", "syndicate", "amazon", "shopee"],
        "content": (
            "Investigation of a syndicated review farm operating across 12 electronics ASINs. "
            "Key Findings: 340 reviews analyzed; 87% contained duplicate n-grams and template phrases like 'Works great very fast shipping high quality'. "
            "Reviewers were compensated via off-platform messaging apps. EchoTrace detected the network by clustering text embeddings "
            "and flagging a 94.2% duplicate text match ratio across 45 user accounts."
        )
    },
    {
        "id": "doc_case_008",
        "title": "Historical Case Study #102: Competitor Negative Sabotage Campaign",
        "category": "case_study",
        "tags": ["case_study", "sabotage", "negative_attack", "competitor"],
        "content": (
            "A malicious seller hired click farms to post 1-star reviews on a competitor's top-selling kitchen appliance. "
            "Linguistic Profile: High toxicity score (> 0.80), repetitive complaint keywords ('dangerous fire hazard return immediately'), "
            "and unverified purchaser status. EchoTrace AI isolated the attack by comparing the sudden toxicity spike against "
            "the product's 6-month historical baseline trust score."
        )
    },
    {
        "id": "doc_benchmark_009",
        "title": "EchoTrace Trust Score Computation & Audit Thresholds",
        "category": "benchmark",
        "tags": ["trust_score", "formula", "thresholds", "risk_levels", "metrics"],
        "content": (
            "EchoTrace calculates an overall Product Trust Score (0% to 100%) based on weighted AI factors: "
            "1) Fake Review Ratio (40% weight): Percentage of reviews flagged as suspicious by TF-IDF + Logistic Regression model. "
            "2) Duplicate Content Ratio (25% weight): Proportion of reviews sharing >= 75% similarity. "
            "3) Rating-Sentiment Alignment (20% weight): Consistency between star ratings and NLP sentiment scores. "
            "4) Toxicity & Spam Index (15% weight). "
            "Trust Score Classifications: "
            "• 80% - 100%: Authentic Product (Low Risk) "
            "• 60% - 79%: Moderate Caution (Medium Risk) "
            "• 0% - 59%: High Manipulation Warning (High Risk - Flagged for Seller Audit)"
        )
    }
]

def initialize_default_knowledge_base(vector_store, force_reindex=False):
    """Populates the RAG vector store with default domain knowledge if empty or forced."""
    stats = vector_store.get_stats()
    if stats["total_documents"] == 0 or force_reindex:
        print("[RAG KnowledgeBase] Initializing domain knowledge base...")
        vector_store.add_documents_batch(DEFAULT_KNOWLEDGE_DOCUMENTS)
        print(f"[RAG KnowledgeBase] Successfully indexed {len(DEFAULT_KNOWLEDGE_DOCUMENTS)} default documents.")
        return True
    return False
